services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: [ "CMD-SHELL", "rpk cluster health -X brokers=redpanda:9092 | grep -E 'Healthy:.+true'" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      redpanda:
        condition: service_healthy

  redpanda-init:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda-init
    depends_on:
      redpanda:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "rpk topic create users -X brokers=redpanda:9092 || true;
       rpk topic create send-mail -p 4 -X brokers=redpanda:9092 || true;
       rpk topic create mail-logs -X brokers=redpanda:9092 || true"

  redpanda-connect:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: redpanda-connect
    command: [ "run", "/connect.yaml" ]
    depends_on:
      redpanda-init:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./redpanda-connect/pipelines/01-master-pipeline.yaml:/connect.yaml:ro

volumes:
  redpanda-data:
