# Simple flow:
# Postman -> Node API -> Redpanda topic -> Redpanda Connect -> MongoDB

input:
  kafka:
    addresses:
      - redpanda:9092
    topics:
      - users
      - mail-logs
    consumer_group: simple-connect-group
    start_from_oldest: true

pipeline:
  processors:
    - bloblang: |
        root = this
        root._meta.topic = @kafka_topic
        root._meta.processedAt = now()
        root._meta.pipeline = "simple-redpanda-to-mongodb"

output:
  switch:
    cases:
      - check: 'this._meta.topic == "users"'
        output:
          mongodb:
            url: mongodb://host.docker.internal:27017
            database: app
            collection: users
            operation: update-one
            upsert: true
            filter_map: |
              root._id = this.id
            document_map: |
              root."$set" = this

      - check: 'this._meta.topic == "mail-logs"'
        output:
          mongodb:
            url: mongodb://host.docker.internal:27017
            database: app
            collection: mail_logs
            operation: update-one
            upsert: true
            filter_map: |
              root._id = this.id
            document_map: |
              root."$set" = this
