# ============================================================
# PIPELINE 03: Đọc NHIỀU topic → lưu CHUNG vào 1 collection
# Use-case: Fan-in (Gom tụ). Thích hợp làm bảng log tổng hợp.
# ============================================================

input:
  kafka:
    addresses:
      - redpanda:9092
    # Lắng nghe 3 topic
    topics:
      - users
      - orders
      - payments
    consumer_group: connect-03-fanin-group
    start_from_oldest: true

pipeline:
  processors:
    - mapping: |
        root = this
        root.savedAt     = now()
        root.source      = "redpanda-connect"
        # Ghi lại tên topic gốc để sau này vào DB còn biết nó đến từ đâu
        root.sourceTopic = @kafka_topic    

output:
  mongodb:
    url: mongodb://host.docker.internal:27017
    database: app_db
    # Dù là users, orders hay payments thì đều bị nhét chung vào bảng 'all_events'
    collection: all_events    
    operation: insert-one
    document_map: |
      root = this
